# Generated by Django 5.2 on 2025-04-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_milage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milage',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Год регистрации пробега'),
        ),
    ]
